//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheStompingLandLauncher {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheStompingLandLauncher.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add server to server list ... ähnelt.
        /// </summary>
        internal static string addHistoryButton {
            get {
                return ResourceManager.GetString("addHistoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add server to history ähnelt.
        /// </summary>
        internal static string addHistoryTitle {
            get {
                return ResourceManager.GetString("addHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die big water cave entrance ähnelt.
        /// </summary>
        internal static string bigWaterCaveEntrance {
            get {
                return ResourceManager.GetString("bigWaterCaveEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die big water cave exit ähnelt.
        /// </summary>
        internal static string bigWaterCaveExit {
            get {
                return ResourceManager.GetString("bigWaterCaveExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid (not empty) configdir. ähnelt.
        /// </summary>
        internal static string ConfigdirBody {
            get {
                return ResourceManager.GetString("ConfigdirBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: Invalid configdir ähnelt.
        /// </summary>
        internal static string ConfigdirHeader {
            get {
                return ResourceManager.GetString("ConfigdirHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid (not empty) configuration name. ähnelt.
        /// </summary>
        internal static string ConfigurationNameBody {
            get {
                return ResourceManager.GetString("ConfigurationNameBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: Invalid Configuration Name ähnelt.
        /// </summary>
        internal static string ConfigurationNameHeader {
            get {
                return ResourceManager.GetString("ConfigurationNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit server ... ähnelt.
        /// </summary>
        internal static string editHistoryButton {
            get {
                return ResourceManager.GetString("editHistoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit server ähnelt.
        /// </summary>
        internal static string editHistoryTitle {
            get {
                return ResourceManager.GetString("editHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have to shut down yourgame before editing savefiles. Otherwise your changes will be overwritten. ähnelt.
        /// </summary>
        internal static string GameStillRunningBody {
            get {
                return ResourceManager.GetString("GameStillRunningBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game still running? ähnelt.
        /// </summary>
        internal static string GameStillRunningHeader {
            get {
                return ResourceManager.GetString("GameStillRunningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid (not empty) hostname. ähnelt.
        /// </summary>
        internal static string HostnameBody {
            get {
                return ResourceManager.GetString("HostnameBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: Invalid hostname ähnelt.
        /// </summary>
        internal static string HostnameHeader {
            get {
                return ResourceManager.GetString("HostnameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid floating point number for X, Y and Z. ähnelt.
        /// </summary>
        internal static string InvalidPositionBody {
            get {
                return ResourceManager.GetString("InvalidPositionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: Invalid Position ähnelt.
        /// </summary>
        internal static string InvalidPositionHeader {
            get {
                return ResourceManager.GetString("InvalidPositionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: Invalid waypoint name ähnelt.
        /// </summary>
        internal static string InvalidWayPointNameBody {
            get {
                return ResourceManager.GetString("InvalidWayPointNameBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a at least 5 characters long waypoint name. ähnelt.
        /// </summary>
        internal static string InvalidWayPointNameHeader {
            get {
                return ResourceManager.GetString("InvalidWayPointNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid port. (between 1 and 65535) ähnelt.
        /// </summary>
        internal static string PortBody {
            get {
                return ResourceManager.GetString("PortBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: Invalid port ähnelt.
        /// </summary>
        internal static string PortHeader {
            get {
                return ResourceManager.GetString("PortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid server address. (eg. if you want to connect to a local server enter 127.0.0.1:7777) ähnelt.
        /// </summary>
        internal static string ServerAddressBody {
            get {
                return ResourceManager.GetString("ServerAddressBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: Invalid server address ähnelt.
        /// </summary>
        internal static string ServerAddressHeader {
            get {
                return ResourceManager.GetString("ServerAddressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It looks like you are already running a server. You may want to quit it, because otherwise the new server will not start correctly. ähnelt.
        /// </summary>
        internal static string ServerAlreadyRunningBody {
            get {
                return ResourceManager.GetString("ServerAlreadyRunningBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server already running? ähnelt.
        /// </summary>
        internal static string ServerAlreadyRunningHeader {
            get {
                return ResourceManager.GetString("ServerAlreadyRunningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please start the server at least once and the required server safefile will be created. ähnelt.
        /// </summary>
        internal static string ServerSaveNotExistBody {
            get {
                return ResourceManager.GetString("ServerSaveNotExistBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server savefile doesn&apos;t exists ähnelt.
        /// </summary>
        internal static string ServerSaveNotExistHeader {
            get {
                return ResourceManager.GetString("ServerSaveNotExistHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to shutdown the server? All progress from players currently still logged in will be lost. ähnelt.
        /// </summary>
        internal static string ServerShutdownBody {
            get {
                return ResourceManager.GetString("ServerShutdownBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning: Server shutdown? ähnelt.
        /// </summary>
        internal static string ServerShutdownHeader {
            get {
                return ResourceManager.GetString("ServerShutdownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have to shut down your server before editing savefiles. Otherwise your changes will be overwritten. ähnelt.
        /// </summary>
        internal static string ServerStillRunningBody {
            get {
                return ResourceManager.GetString("ServerStillRunningBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server still running? ähnelt.
        /// </summary>
        internal static string ServerStillRunningHeader {
            get {
                return ResourceManager.GetString("ServerStillRunningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, we couldn&apos;t detect your The Stomping Land folder :( Please select your Stomping Land Folder (the one containing Binaries, Engine and UDKGame) in the next dialog. ähnelt.
        /// </summary>
        internal static string SLfolderPathBody {
            get {
                return ResourceManager.GetString("SLfolderPathBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning: Couldn&apos;t detect The Stomping Land folder ähnelt.
        /// </summary>
        internal static string SLfolderPathHeader {
            get {
                return ResourceManager.GetString("SLfolderPathHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please start the solo game modus at least once and the required solo safefile will be created. ähnelt.
        /// </summary>
        internal static string SoloSaveNotExistBody {
            get {
                return ResourceManager.GetString("SoloSaveNotExistBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solo savefile doesn&apos;t exists ähnelt.
        /// </summary>
        internal static string SoloSaveNotExistHeader {
            get {
                return ResourceManager.GetString("SoloSaveNotExistHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die southern lake ähnelt.
        /// </summary>
        internal static string southernLake {
            get {
                return ResourceManager.GetString("southernLake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid SteamQueryPort. (between 1 and 65535) ähnelt.
        /// </summary>
        internal static string SteamQueryPortBody {
            get {
                return ResourceManager.GetString("SteamQueryPortBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: Invalid SteamQueryPort ähnelt.
        /// </summary>
        internal static string SteamQueryPortHeader {
            get {
                return ResourceManager.GetString("SteamQueryPortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die vulcano ähnelt.
        /// </summary>
        internal static string vulcano {
            get {
                return ResourceManager.GetString("vulcano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die vulcano cave entrance ähnelt.
        /// </summary>
        internal static string vulcanoCaveEntrance {
            get {
                return ResourceManager.GetString("vulcanoCaveEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waterfall cave ähnelt.
        /// </summary>
        internal static string waterfallCave {
            get {
                return ResourceManager.GetString("waterfallCave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die western river mouth ähnelt.
        /// </summary>
        internal static string westernRiverMouth {
            get {
                return ResourceManager.GetString("westernRiverMouth", resourceCulture);
            }
        }
    }
}
